export const MockStargazerModels = {
    "data": {
        "search": {
            "nodes": [{
                "repositoryTopics": {
                    "nodes": [{
                        "topic": {
                            "name": "polymer",
                            "stargazerCount": 8,
                            "relatedTopics": [{
                                "name": "polymer-application",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "service-worker",
                                "stargazerCount": 22,
                                "__typename": "Topic"
                            }, {
                                "name": "prpl-pattern",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "demand",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "polymer-cli",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "optimizations",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "litelement",
                                "stargazerCount": 1,
                                "__typename": "Topic"
                            }, {
                                "name": "launchpad",
                                "stargazerCount": 3,
                                "__typename": "Topic"
                            }, {
                                "name": "vercel",
                                "stargazerCount": 122,
                                "__typename": "Topic"
                            }, {
                                "name": "webcomponents",
                                "stargazerCount": 21,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "webcomponents",
                            "stargazerCount": 21,
                            "relatedTopics": [{
                                "name": "polymer",
                                "stargazerCount": 8,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "demo",
                                "stargazerCount": 17,
                                "__typename": "Topic"
                            }, {
                                "name": "litelement",
                                "stargazerCount": 1,
                                "__typename": "Topic"
                            }, {
                                "name": "angular",
                                "stargazerCount": 28969,
                                "__typename": "Topic"
                            }, {
                                "name": "shadow-dom",
                                "stargazerCount": 6,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }, {
                                "name": "html",
                                "stargazerCount": 52798,
                                "__typename": "Topic"
                            }, {
                                "name": "stencil",
                                "stargazerCount": 8,
                                "__typename": "Topic"
                            }, {
                                "name": "eslint",
                                "stargazerCount": 6368,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "frontend",
                            "stargazerCount": 19361,
                            "relatedTopics": [{
                                "name": "backend",
                                "stargazerCount": 248,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "sanity",
                                "stargazerCount": 2,
                                "__typename": "Topic"
                            }, {
                                "name": "database",
                                "stargazerCount": 30591,
                                "__typename": "Topic"
                            }, {
                                "name": "gatsby",
                                "stargazerCount": 188,
                                "__typename": "Topic"
                            }, {
                                "name": "stack",
                                "stargazerCount": 23,
                                "__typename": "Topic"
                            }, {
                                "name": "netlify",
                                "stargazerCount": 25,
                                "__typename": "Topic"
                            }, {
                                "name": "docker",
                                "stargazerCount": 35606,
                                "__typename": "Topic"
                            }, {
                                "name": "studio",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "home-assistant",
                            "stargazerCount": 269,
                            "relatedTopics": [{
                                "name": "hassio",
                                "stargazerCount": 30,
                                "__typename": "Topic"
                            }, {
                                "name": "home-assistant-config",
                                "stargazerCount": 71,
                                "__typename": "Topic"
                            }, {
                                "name": "home-assistant-configuration",
                                "stargazerCount": 8,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "home-automation",
                            "stargazerCount": 81,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "lit-element",
                            "stargazerCount": 10,
                            "relatedTopics": [{
                                "name": "vscode",
                                "stargazerCount": 99,
                                "__typename": "Topic"
                            }, {
                                "name": "lit-html",
                                "stargazerCount": 6,
                                "__typename": "Topic"
                            }, {
                                "name": "workbox",
                                "stargazerCount": 2,
                                "__typename": "Topic"
                            }, {
                                "name": "polymer",
                                "stargazerCount": 8,
                                "__typename": "Topic"
                            }, {
                                "name": "typescript",
                                "stargazerCount": 17051,
                                "__typename": "Topic"
                            }, {
                                "name": "webpack",
                                "stargazerCount": 7497,
                                "__typename": "Topic"
                            }, {
                                "name": "litelement",
                                "stargazerCount": 1,
                                "__typename": "Topic"
                            }, {
                                "name": "service-workers",
                                "stargazerCount": 7,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "hacktoberfest",
                            "stargazerCount": 5128,
                            "relatedTopics": [{
                                "name": "star",
                                "stargazerCount": 9,
                                "__typename": "Topic"
                            }, {
                                "name": "prs",
                                "stargazerCount": 1,
                                "__typename": "Topic"
                            }, {
                                "name": "language",
                                "stargazerCount": 2000,
                                "__typename": "Topic"
                            }, {
                                "name": "challenge",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }, {
                                "name": "register",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "celebration",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "profile",
                                "stargazerCount": 9,
                                "__typename": "Topic"
                            }, {
                                "name": "spam",
                                "stargazerCount": 4,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }],
                    "__typename": "RepositoryTopicConnection"
                },
                "__typename": "Repository"
            }, {
                "repositoryTopics": {
                    "nodes": [{
                        "topic": {
                            "name": "journalism",
                            "stargazerCount": 43,
                            "relatedTopics": [{
                                "name": "advertising",
                                "stargazerCount": 17,
                                "__typename": "Topic"
                            }, {
                                "name": "gitbook",
                                "stargazerCount": 39,
                                "__typename": "Topic"
                            }, {
                                "name": "media-studies",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "data-journalism",
                                "stargazerCount": 25,
                                "__typename": "Topic"
                            }, {
                                "name": "data-analysis",
                                "stargazerCount": 317,
                                "__typename": "Topic"
                            }, {
                                "name": "university",
                                "stargazerCount": 18,
                                "__typename": "Topic"
                            }, {
                                "name": "news",
                                "stargazerCount": 43,
                                "__typename": "Topic"
                            }, {
                                "name": "students",
                                "stargazerCount": 17,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }],
                    "__typename": "RepositoryTopicConnection"
                },
                "__typename": "Repository"
            }, {
                "repositoryTopics": {
                    "nodes": [],
                    "__typename": "RepositoryTopicConnection"
                },
                "__typename": "Repository"
            }, {
                "repositoryTopics": {
                    "nodes": [{
                        "topic": {
                            "name": "frontend",
                            "stargazerCount": 19361,
                            "relatedTopics": [{
                                "name": "backend",
                                "stargazerCount": 248,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "sanity",
                                "stargazerCount": 2,
                                "__typename": "Topic"
                            }, {
                                "name": "database",
                                "stargazerCount": 30591,
                                "__typename": "Topic"
                            }, {
                                "name": "gatsby",
                                "stargazerCount": 188,
                                "__typename": "Topic"
                            }, {
                                "name": "stack",
                                "stargazerCount": 23,
                                "__typename": "Topic"
                            }, {
                                "name": "netlify",
                                "stargazerCount": 25,
                                "__typename": "Topic"
                            }, {
                                "name": "docker",
                                "stargazerCount": 35606,
                                "__typename": "Topic"
                            }, {
                                "name": "studio",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "clojure",
                            "stargazerCount": 4108,
                            "relatedTopics": [{
                                "name": "cljs",
                                "stargazerCount": 21,
                                "__typename": "Topic"
                            }, {
                                "name": "clojurescript",
                                "stargazerCount": 75,
                                "__typename": "Topic"
                            }, {
                                "name": "language",
                                "stargazerCount": 2000,
                                "__typename": "Topic"
                            }, {
                                "name": "eclipse",
                                "stargazerCount": 56,
                                "__typename": "Topic"
                            }, {
                                "name": "clojurescript-repl",
                                "stargazerCount": 1,
                                "__typename": "Topic"
                            }, {
                                "name": "repl",
                                "stargazerCount": 20,
                                "__typename": "Topic"
                            }, {
                                "name": "advent",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "clj",
                                "stargazerCount": 8,
                                "__typename": "Topic"
                            }, {
                                "name": "java",
                                "stargazerCount": 83042,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "clojurescript",
                            "stargazerCount": 75,
                            "relatedTopics": [{
                                "name": "clj",
                                "stargazerCount": 8,
                                "__typename": "Topic"
                            }, {
                                "name": "clojure",
                                "stargazerCount": 4108,
                                "__typename": "Topic"
                            }, {
                                "name": "language",
                                "stargazerCount": 2000,
                                "__typename": "Topic"
                            }, {
                                "name": "shadow-cljs",
                                "stargazerCount": 4,
                                "__typename": "Topic"
                            }, {
                                "name": "cljs",
                                "stargazerCount": 21,
                                "__typename": "Topic"
                            }, {
                                "name": "reagent",
                                "stargazerCount": 4,
                                "__typename": "Topic"
                            }, {
                                "name": "figwheel",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "repl",
                                "stargazerCount": 20,
                                "__typename": "Topic"
                            }, {
                                "name": "frame",
                                "stargazerCount": 52,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "om",
                            "stargazerCount": 1,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }],
                    "__typename": "RepositoryTopicConnection"
                },
                "__typename": "Repository"
            }, {
                "repositoryTopics": {
                    "nodes": [{
                        "topic": {
                            "name": "kottans",
                            "stargazerCount": 2,
                            "relatedTopics": [{
                                "name": "kottans-frontend",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "javascript-oop",
                                "stargazerCount": 1,
                                "__typename": "Topic"
                            }, {
                                "name": "oop",
                                "stargazerCount": 37,
                                "__typename": "Topic"
                            }, {
                                "name": "oriented-programing",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }, {
                                "name": "practice",
                                "stargazerCount": 23,
                                "__typename": "Topic"
                            }, {
                                "name": "html",
                                "stargazerCount": 52798,
                                "__typename": "Topic"
                            }, {
                                "name": "collaboration",
                                "stargazerCount": 54,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "learning",
                            "stargazerCount": 496,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "javascript",
                            "stargazerCount": 85145,
                            "relatedTopics": [{
                                "name": "nodejs",
                                "stargazerCount": 37420,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }, {
                                "name": "html",
                                "stargazerCount": 52798,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "typescript",
                                "stargazerCount": 17051,
                                "__typename": "Topic"
                            }, {
                                "name": "webpack",
                                "stargazerCount": 7497,
                                "__typename": "Topic"
                            }, {
                                "name": "game",
                                "stargazerCount": 941,
                                "__typename": "Topic"
                            }, {
                                "name": "jquery",
                                "stargazerCount": 16207,
                                "__typename": "Topic"
                            }, {
                                "name": "jekyll",
                                "stargazerCount": 3679,
                                "__typename": "Topic"
                            }, {
                                "name": "challenge",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "self-learning",
                            "stargazerCount": 23,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "frontend",
                            "stargazerCount": 19361,
                            "relatedTopics": [{
                                "name": "backend",
                                "stargazerCount": 248,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "sanity",
                                "stargazerCount": 2,
                                "__typename": "Topic"
                            }, {
                                "name": "database",
                                "stargazerCount": 30591,
                                "__typename": "Topic"
                            }, {
                                "name": "gatsby",
                                "stargazerCount": 188,
                                "__typename": "Topic"
                            }, {
                                "name": "stack",
                                "stargazerCount": 23,
                                "__typename": "Topic"
                            }, {
                                "name": "netlify",
                                "stargazerCount": 25,
                                "__typename": "Topic"
                            }, {
                                "name": "docker",
                                "stargazerCount": 35606,
                                "__typename": "Topic"
                            }, {
                                "name": "studio",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "css",
                            "stargazerCount": 45732,
                            "relatedTopics": [{
                                "name": "html",
                                "stargazerCount": 52798,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "challenge",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }, {
                                "name": "bootstrap",
                                "stargazerCount": 35146,
                                "__typename": "Topic"
                            }, {
                                "name": "javascript",
                                "stargazerCount": 85145,
                                "__typename": "Topic"
                            }, {
                                "name": "vercel",
                                "stargazerCount": 122,
                                "__typename": "Topic"
                            }, {
                                "name": "css-preprocessors",
                                "stargazerCount": 7,
                                "__typename": "Topic"
                            }, {
                                "name": "frontend-mentor",
                                "stargazerCount": 9,
                                "__typename": "Topic"
                            }, {
                                "name": "react-components",
                                "stargazerCount": 78,
                                "__typename": "Topic"
                            }, {
                                "name": "workflow",
                                "stargazerCount": 67,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "frontend-course",
                            "stargazerCount": 0,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "html",
                            "stargazerCount": 52798,
                            "relatedTopics": [{
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }, {
                                "name": "challenge",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "gitpod",
                                "stargazerCount": 8,
                                "__typename": "Topic"
                            }, {
                                "name": "vercel",
                                "stargazerCount": 122,
                                "__typename": "Topic"
                            }, {
                                "name": "bootstrap",
                                "stargazerCount": 35146,
                                "__typename": "Topic"
                            }, {
                                "name": "javascript",
                                "stargazerCount": 85145,
                                "__typename": "Topic"
                            }, {
                                "name": "robot",
                                "stargazerCount": 85,
                                "__typename": "Topic"
                            }, {
                                "name": "css-preprocessors",
                                "stargazerCount": 7,
                                "__typename": "Topic"
                            }, {
                                "name": "github-page",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "friendship",
                            "stargazerCount": 4,
                            "relatedTopics": [{
                                "name": "demeter",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "complexity",
                                "stargazerCount": 5,
                                "__typename": "Topic"
                            }, {
                                "name": "artists",
                                "stargazerCount": 6,
                                "__typename": "Topic"
                            }, {
                                "name": "songs",
                                "stargazerCount": 7,
                                "__typename": "Topic"
                            }, {
                                "name": "dot",
                                "stargazerCount": 12,
                                "__typename": "Topic"
                            }, {
                                "name": "lab",
                                "stargazerCount": 5,
                                "__typename": "Topic"
                            }, {
                                "name": "friend",
                                "stargazerCount": 1,
                                "__typename": "Topic"
                            }, {
                                "name": "rails",
                                "stargazerCount": 6225,
                                "__typename": "Topic"
                            }, {
                                "name": "dataset",
                                "stargazerCount": 144,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }],
                    "__typename": "RepositoryTopicConnection"
                },
                "__typename": "Repository"
            }, {
                "repositoryTopics": {
                    "nodes": [{
                        "topic": {
                            "name": "javascript",
                            "stargazerCount": 85145,
                            "relatedTopics": [{
                                "name": "nodejs",
                                "stargazerCount": 37420,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }, {
                                "name": "html",
                                "stargazerCount": 52798,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "typescript",
                                "stargazerCount": 17051,
                                "__typename": "Topic"
                            }, {
                                "name": "webpack",
                                "stargazerCount": 7497,
                                "__typename": "Topic"
                            }, {
                                "name": "game",
                                "stargazerCount": 941,
                                "__typename": "Topic"
                            }, {
                                "name": "jquery",
                                "stargazerCount": 16207,
                                "__typename": "Topic"
                            }, {
                                "name": "jekyll",
                                "stargazerCount": 3679,
                                "__typename": "Topic"
                            }, {
                                "name": "challenge",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "couchdb",
                            "stargazerCount": 9,
                            "relatedTopics": [{
                                "name": "database",
                                "stargazerCount": 30591,
                                "__typename": "Topic"
                            }, {
                                "name": "docker",
                                "stargazerCount": 35606,
                                "__typename": "Topic"
                            }, {
                                "name": "cloudant",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "hyperledger-fabric",
                                "stargazerCount": 13,
                                "__typename": "Topic"
                            }, {
                                "name": "fabric",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }, {
                                "name": "mongodb",
                                "stargazerCount": 15302,
                                "__typename": "Topic"
                            }, {
                                "name": "couchdb-database",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "elasticsearch",
                                "stargazerCount": 169,
                                "__typename": "Topic"
                            }, {
                                "name": "backend",
                                "stargazerCount": 248,
                                "__typename": "Topic"
                            }, {
                                "name": "json",
                                "stargazerCount": 21491,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "emr",
                            "stargazerCount": 3,
                            "relatedTopics": [{
                                "name": "spark",
                                "stargazerCount": 266,
                                "__typename": "Topic"
                            }, {
                                "name": "data-lake",
                                "stargazerCount": 6,
                                "__typename": "Topic"
                            }, {
                                "name": "cluster",
                                "stargazerCount": 19,
                                "__typename": "Topic"
                            }, {
                                "name": "emr-cluster",
                                "stargazerCount": 2,
                                "__typename": "Topic"
                            }, {
                                "name": "pyspark",
                                "stargazerCount": 47,
                                "__typename": "Topic"
                            }, {
                                "name": "airflow",
                                "stargazerCount": 29,
                                "__typename": "Topic"
                            }, {
                                "name": "etl-pipeline",
                                "stargazerCount": 15,
                                "__typename": "Topic"
                            }, {
                                "name": "s3-bucket",
                                "stargazerCount": 2,
                                "__typename": "Topic"
                            }, {
                                "name": "sparkify",
                                "stargazerCount": 0,
                                "__typename": "Topic"
                            }, {
                                "name": "hadoop",
                                "stargazerCount": 151,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "open-healthcare",
                            "stargazerCount": 1,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "pouchdb",
                            "stargazerCount": 5,
                            "relatedTopics": [{
                                "name": "database",
                                "stargazerCount": 30591,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "offline",
                                "stargazerCount": 10,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "hospitalrun",
                            "stargazerCount": 2,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "frontend",
                            "stargazerCount": 19361,
                            "relatedTopics": [{
                                "name": "backend",
                                "stargazerCount": 248,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "sanity",
                                "stargazerCount": 2,
                                "__typename": "Topic"
                            }, {
                                "name": "database",
                                "stargazerCount": 30591,
                                "__typename": "Topic"
                            }, {
                                "name": "gatsby",
                                "stargazerCount": 188,
                                "__typename": "Topic"
                            }, {
                                "name": "stack",
                                "stargazerCount": 23,
                                "__typename": "Topic"
                            }, {
                                "name": "netlify",
                                "stargazerCount": 25,
                                "__typename": "Topic"
                            }, {
                                "name": "docker",
                                "stargazerCount": 35606,
                                "__typename": "Topic"
                            }, {
                                "name": "studio",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "hospitalrun-frontend",
                            "stargazerCount": 1,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "react",
                            "stargazerCount": 47076,
                            "relatedTopics": [{
                                "name": "angular",
                                "stargazerCount": 28969,
                                "__typename": "Topic"
                            }, {
                                "name": "react-native",
                                "stargazerCount": 16163,
                                "__typename": "Topic"
                            }, {
                                "name": "vue",
                                "stargazerCount": 35467,
                                "__typename": "Topic"
                            }, {
                                "name": "minify",
                                "stargazerCount": 5,
                                "__typename": "Topic"
                            }, {
                                "name": "redux",
                                "stargazerCount": 8348,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }, {
                                "name": "css-preprocessors",
                                "stargazerCount": 7,
                                "__typename": "Topic"
                            }, {
                                "name": "bootstrap",
                                "stargazerCount": 35146,
                                "__typename": "Topic"
                            }, {
                                "name": "html",
                                "stargazerCount": 52798,
                                "__typename": "Topic"
                            }, {
                                "name": "typescript",
                                "stargazerCount": 17051,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "redux",
                            "stargazerCount": 8348,
                            "relatedTopics": [{
                                "name": "javascript",
                                "stargazerCount": 85145,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "minify",
                                "stargazerCount": 5,
                                "__typename": "Topic"
                            }, {
                                "name": "typescript",
                                "stargazerCount": 17051,
                                "__typename": "Topic"
                            }, {
                                "name": "firebase",
                                "stargazerCount": 14089,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }, {
                                "name": "props",
                                "stargazerCount": 4,
                                "__typename": "Topic"
                            }, {
                                "name": "boilerplate",
                                "stargazerCount": 66,
                                "__typename": "Topic"
                            }, {
                                "name": "mongodb",
                                "stargazerCount": 15302,
                                "__typename": "Topic"
                            }, {
                                "name": "backend",
                                "stargazerCount": 248,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }],
                    "__typename": "RepositoryTopicConnection"
                },
                "__typename": "Repository"
            }, {
                "repositoryTopics": {
                    "nodes": [],
                    "__typename": "RepositoryTopicConnection"
                },
                "__typename": "Repository"
            }, {
                "repositoryTopics": {
                    "nodes": [],
                    "__typename": "RepositoryTopicConnection"
                },
                "__typename": "Repository"
            }, {
                "repositoryTopics": {
                    "nodes": [{
                        "topic": {
                            "name": "frontend",
                            "stargazerCount": 19361,
                            "relatedTopics": [{
                                "name": "backend",
                                "stargazerCount": 248,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "sanity",
                                "stargazerCount": 2,
                                "__typename": "Topic"
                            }, {
                                "name": "database",
                                "stargazerCount": 30591,
                                "__typename": "Topic"
                            }, {
                                "name": "gatsby",
                                "stargazerCount": 188,
                                "__typename": "Topic"
                            }, {
                                "name": "stack",
                                "stargazerCount": 23,
                                "__typename": "Topic"
                            }, {
                                "name": "netlify",
                                "stargazerCount": 25,
                                "__typename": "Topic"
                            }, {
                                "name": "docker",
                                "stargazerCount": 35606,
                                "__typename": "Topic"
                            }, {
                                "name": "studio",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "awesome-list",
                            "stargazerCount": 555,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "awesome",
                            "stargazerCount": 31003,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "list",
                            "stargazerCount": 42,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }],
                    "__typename": "RepositoryTopicConnection"
                },
                "__typename": "Repository"
            }, {
                "repositoryTopics": {
                    "nodes": [{
                        "topic": {
                            "name": "vue",
                            "stargazerCount": 35467,
                            "relatedTopics": [{
                                "name": "angular",
                                "stargazerCount": 28969,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "laravel",
                                "stargazerCount": 14463,
                                "__typename": "Topic"
                            }, {
                                "name": "demo",
                                "stargazerCount": 17,
                                "__typename": "Topic"
                            }, {
                                "name": "javascript",
                                "stargazerCount": 85145,
                                "__typename": "Topic"
                            }, {
                                "name": "webpack",
                                "stargazerCount": 7497,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }, {
                                "name": "typescript",
                                "stargazerCount": 17051,
                                "__typename": "Topic"
                            }, {
                                "name": "vue-router",
                                "stargazerCount": 23,
                                "__typename": "Topic"
                            }, {
                                "name": "frontend",
                                "stargazerCount": 19361,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "javascript",
                            "stargazerCount": 85145,
                            "relatedTopics": [{
                                "name": "nodejs",
                                "stargazerCount": 37420,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }, {
                                "name": "html",
                                "stargazerCount": 52798,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "typescript",
                                "stargazerCount": 17051,
                                "__typename": "Topic"
                            }, {
                                "name": "webpack",
                                "stargazerCount": 7497,
                                "__typename": "Topic"
                            }, {
                                "name": "game",
                                "stargazerCount": 941,
                                "__typename": "Topic"
                            }, {
                                "name": "jquery",
                                "stargazerCount": 16207,
                                "__typename": "Topic"
                            }, {
                                "name": "jekyll",
                                "stargazerCount": 3679,
                                "__typename": "Topic"
                            }, {
                                "name": "challenge",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "frontend",
                            "stargazerCount": 19361,
                            "relatedTopics": [{
                                "name": "backend",
                                "stargazerCount": 248,
                                "__typename": "Topic"
                            }, {
                                "name": "react",
                                "stargazerCount": 47076,
                                "__typename": "Topic"
                            }, {
                                "name": "sanity",
                                "stargazerCount": 2,
                                "__typename": "Topic"
                            }, {
                                "name": "database",
                                "stargazerCount": 30591,
                                "__typename": "Topic"
                            }, {
                                "name": "gatsby",
                                "stargazerCount": 188,
                                "__typename": "Topic"
                            }, {
                                "name": "stack",
                                "stargazerCount": 23,
                                "__typename": "Topic"
                            }, {
                                "name": "netlify",
                                "stargazerCount": 25,
                                "__typename": "Topic"
                            }, {
                                "name": "docker",
                                "stargazerCount": 35606,
                                "__typename": "Topic"
                            }, {
                                "name": "studio",
                                "stargazerCount": 16,
                                "__typename": "Topic"
                            }, {
                                "name": "css",
                                "stargazerCount": 45732,
                                "__typename": "Topic"
                            }],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }, {
                        "topic": {
                            "name": "framework",
                            "stargazerCount": 14865,
                            "relatedTopics": [],
                            "__typename": "Topic"
                        },
                        "__typename": "RepositoryTopic"
                    }],
                    "__typename": "RepositoryTopicConnection"
                },
                "__typename": "Repository"
            }],
            "__typename": "SearchResultItemConnection"
        }
    }
}